# Site settings
title: Hi :)))
baseurl: ""
url: "https://muteyaki.github.io"
google_analytics: "G-P0HJHFKQ3G"

# Author
author:
  name: Guoxin Shi
  desc: Science & Art.
  email: guoxinshimay@outlook.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: muteyaki
  google_scholar: https://scholar.google.com.hk/citations?user=dQm5ZkEAAAAJ&hl=en
  google_plus:
  instagram: mantemiya_
  keybase:
  linkedin: 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

collections:
  photography:
    output: true
    permalink: /photography/:path/

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/blog/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "README.md"
